---
title: "Senarai Ahli Baharu"
author: "Sekretariat"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(dplyr)
library(janitor)
library(knitr)
library(googlesheets4)

load("bre.RData")
# read google spreadsheet file from google drive ----
ss <- gs4_get("https://docs.google.com/spreadsheets/d/1R_aJ9YPp4IiQZfu1RTw4KLWq5155uCvnu0OuVG_H2q8/edit#gid=1295676957")
rs <- read_sheet(ss, sheet = 1) %>% 
  clean_names() %>%
  rename(no_kp = no_kad_pengenalan_mykad, pkt = pangkat_ketika_bersara) %>%
  mutate(no_kp = as.character(no_kp),
         no_kp = stringr::str_replace_all(no_kp," ",""),
         no_kp = stringr::str_replace_all(no_kp,"-",""),
         no_tentera = stringr::str_replace_all(no_tentera,"N|T|/",""),
         alamat = stringr::str_replace_all(alamat,"\n"," ")) %>% 
  filter(no_kp != "") %>% 
  filter(nama != "") %>% 
  distinct(no_kp, .keep_all = TRUE)

# new bre_2 batch, no_kp not in rs ----
bre_2 <- rs %>% 
  anti_join(bre_1, by = "no_kp") %>% 
  select(no_kp, nama, e_mail, pkt, no_tel)

# save bre_1, bre_2 ----
save(bre_1,bre_2, rs, file = "bre.RData")
```

## Selamat Datang Ahli Baharu
Senarai ahli baharu yang telah mendaftar sebagai ahli RAFOC pada tahun 2023.

```{r ahli}
# print list of new members ----
rs %>% 
  mutate(nama = stringr::str_to_title(nama)) %>% 
  select(no_tentera, nama, pkt) %>%
  knitr::kable(caption = "Senarai Ahli Baharu", row.names = TRUE,
               col.names = c("Siri", "No. Tentera", "Nama", "Pangkat"))
```

Jumlah pada 31 Dis 2022: 748 orang    
Daftar 1 Jan 2023 -  `r format(Sys.Date(),"%d %b %Y")`: `r nrow(rs)` orang    
Jumlah Keseluruhan : `r nrow(rs) + 748` orang

```{r by_pkt}
# group by pkt ----
rs %>% 
  group_by(pkt) %>%
  summarise(n = n()) %>%
  knitr::kable(caption = "Jumlah Ahli Baharu Mengikut Pangkat", row.names = TRUE,
               col.names = c("Pangkat", "Jumlah"))
```
