---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

## Semak Pangkalan Data
The script connects to a MongoDB database, retrieves data from a Google Spreadsheet, and updates the MongoDB collection (ahli) with the data from the spreadsheet.

```{r init}

library(mongolite)
library(dplyr)
library(jsonlite)
library(googlesheets4)
library(kableExtra)

# Load db ----
MG_URL <- Sys.getenv("MG_URL")
db <- mongo(collection = "minit", db = "rafoc", url = MG_URL)

# Get doc from db ----
siri <- "3/24"
jenis <- "exco"
doc <- list(Siri = siri, Jenis = jenis)
query <- toJSON(doc, auto_unbox = TRUE) %>% 
  as.character()
```

# Kemaskini Senarai Kehadiran

```{r Get att list and update}

n <- nrow(db$find(query))

if(n==0 || nchar(siri)>4 || jenis != "exco") {
  tryCatch({
    message('Oops! Doc not found')
  })
} else {
  # Get attendance list from Google sheet ----
  # in folder rafoc <- mesy jk <- ajk
  ss <- gs4_get("https://docs.google.com/spreadsheets/d/1WUpXso8buhZAgC1Ya4uFGTFw3fiTE4ligyAFfPJ_nt4/edit#gid=0")
  dfy <- read_sheet(ss, sheet = 1) %>% 
    select(Nama, Singkatan, Jawatan, Hadir) %>% 
    filter(Hadir == "Ya")
  dft <- read_sheet(ss, sheet = 1) %>% 
    filter(Hadir == "Tidak")
  
  # Update document
  update_document <- list(
    "$set" = list(
      Hadir = list(
        Nama = dfy$Nama,
        Singkatan = dfy$Singkatan,
        Jawatan = dfy$Jawatan
      ),
      Tidak_hadir = list(
        Nama = dft$Nama,
        Singkatan = dft$Singkatan,
        Jawatan = dft$Jawatan
      )
    )
  )
  
  # Convert the update document to JSON
  update_json <- jsonlite::toJSON(update_document, auto_unbox = TRUE)
  
  # Perform the update operation
  db$update(
    query = query,
    update = update_json,
    upsert = TRUE
  )
}
```

## Minit Exco

```{r print minutes of meeting, echo=FALSE}
# minit <- db$find(query) 
# Try to find the document
n <- nrow(db$find(query))

if(n==0 || nchar(siri)>4 || jenis != "exco") {
  tryCatch({
    message('Oops! Doc not found')
  })
} else {
  # source("ahli_rs.R")
  minit <- db$find(query)
  load("ahli.RData")
  rmarkdown::render("minit_exco_prt.Rmd",output_file = "minit_exco.pdf")
}

```
## Maklum Balas Minit Exco

```{r print, echo=FALSE}
# Get doc from db ----
siri <- paste0(substr(siri,1,1),"m",substr(siri,2,5))
jenis <- "exco"
doc <- list(Siri = siri, Jenis = jenis)
query <- toJSON(doc, auto_unbox = TRUE) %>% 
  as.character()
n <- nrow(db$find(query))

if(n==0 || nchar(siri)<5) {
  tryCatch({
    message('Oops! Doc not found')
  })
} else {
  minit <- db$find(query) 
  load("ahli.RData")
  rmarkdown::render("minit_exco_mbls.Rmd",output_file = "maklumbalas_exco.pdf")
}
```
## Mesyuarat MMMT

```{r mm}
# Get doc from db ----
siri <- "3/24"
jenis <- "mmmt"
doc <- list(Siri = siri, Jenis = jenis)
query <- toJSON(doc, auto_unbox = TRUE) %>% 
  as.character()
n <- nrow(db$find(query))

if(n==0 || nchar(siri)>4 || jenis != "mmmt") {
  tryCatch({
    message('Oops! Doc not found')
  })
} else {
  minit <- db$find(query)
  rmarkdown::render("minit_mmmt.Rmd",output_file = "minit_mmmt.pdf")
}
```

