# Perjuangan Veteran

1. Veteran ATM berbekal pengalaman yang ada pada anggota tersebut sepanjang perkhidmatan dengan ATM dapat menyumbang kepada ekonomi negara. Jumlah mereka adalah xxxx . Kertas Putih Pertahanan (KPP) turut menggariskan kepentingan terhadap usaha menghasilkan kerjaya kedua kepada anggota ATM selepas mereka bersara daripada perkhidmatan kelak. Kehidupan veteran pasca perkhidmatan hendaklah membolehkan mereka dan keluarga terus hidup selesa dan selamat. Pengalaman sepanjang tempoh perkhidmatan yang diperolehi dan nilai disiplin yang tinggi adalah aset penting dan mengupayakan veteran untuk kelangsungan hidup.
	* Ideal
		* 
		* Kertas Putih Pertahanan
			* menfokuskan 
			* mewujudkan lebih banyak peluang pekerjaan dalam perkhidmatan ATM
	* keadaan semasa
		* anggota tentera bertanya, apakah kerajaan lakukan.
			* menambahkan anggota tentera mahir
			* melakukan demonstrasi
			* provokasi yang boleh membawa kepada ancaman dan ketenteraman awam
			* Defisit kepercayaan
			* aging veteran
			* rasa kurang puas hati dengan keadaan dalam angkatan tentera
		* Sosio-ekonomi
			* mewajibkan semua anggota tentera yang menamatkan perkhidmatan.
			* merosakkan imej
			* Perumahan & pekerjaan
				* firma-firma untuk ambil veteran
			* umur 40
				* anak sedang membesar
			* kemudahan perubatan
				* hospital veteran
			* kebajikan bekas-bekas tentera ini terjaga dan terbela
	* Penyelesaian
		* langkah-langkah kementerian dalam membela nasib dan kebajikan anggota tentera
		* JHEV
			* Bantuan Insentif Khas Insurgensi veteran ATM
			* BSH
			* persatuan tentera mampu lakukan tentulah terbatas kerana tidak ada peruntukan tertentu dari pihak kerajaan.
			* membela nasib bekas angkatan tentera
		* pendidikan akan dapat meningkatkan pencapaian prestasi
			* Skim pinjaman akademik anak-anak tentera
			* tabung pelajaran kanak-kanak angkatan tentera.
	* Outcome
		* kerjaya tentera akan menjadi kerjaya pilihan generasi
		* membantu bekas tentera umpama membantu kerajaan
		* bekas-bekas tentera ini akan menyokong Kerajaan
